# This yaml file contains information about hyper-parameters of the model
AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # required by VGG-16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 20
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01